POST http://localhost:3003/api/blogs/ 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZyaWRheSIsImlkIjoiNWZhNTM1YWEwYjIyM2Y3YzE4ZWQzNWI5IiwiaWF0IjoxNjA0NjYzMDE0fQ.QSddwoh5ov5Wm3AVxSP0ocldpMd3t-FvfL7ivUdBJs0

{
    "url": "www.Friday.com",
    "title": "Friday is the best day!",
    "author": "Heidi K",
    "likes": 500
}